// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Example_Temp.Models;

#nullable disable

namespace Web_Example_Temp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240609074442_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Web_Example_Temp.Models.Okul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Okullar");
                });

            modelBuilder.Entity("Web_Example_Temp.Models.Veli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Veliler");
                });

            modelBuilder.Entity("Web_Example_Temp.Models.Öğrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("OkulId")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("OkulId");

                    b.ToTable("Öğrenciler");
                });

            modelBuilder.Entity("Web_Example_Temp.Models.ÖğrenciVeli", b =>
                {
                    b.Property<int>("ÖğrenciId")
                        .HasColumnType("int");

                    b.Property<int>("VeliId")
                        .HasColumnType("int");

                    b.HasKey("ÖğrenciId", "VeliId");

                    b.HasIndex("VeliId");

                    b.ToTable("ÖğrenciVeliler");
                });

            modelBuilder.Entity("Web_Example_Temp.Models.Öğrenci", b =>
                {
                    b.HasOne("Web_Example_Temp.Models.Okul", "Okul")
                        .WithMany("Öğrenciler")
                        .HasForeignKey("OkulId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Okul");
                });

            modelBuilder.Entity("Web_Example_Temp.Models.ÖğrenciVeli", b =>
                {
                    b.HasOne("Web_Example_Temp.Models.Veli", "Veli")
                        .WithMany("ÖğrenciVeliler")
                        .HasForeignKey("VeliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_Example_Temp.Models.Öğrenci", "Öğrenci")
                        .WithMany("ÖğrenciVeliler")
                        .HasForeignKey("ÖğrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Veli");

                    b.Navigation("Öğrenci");
                });

            modelBuilder.Entity("Web_Example_Temp.Models.Okul", b =>
                {
                    b.Navigation("Öğrenciler");
                });

            modelBuilder.Entity("Web_Example_Temp.Models.Veli", b =>
                {
                    b.Navigation("ÖğrenciVeliler");
                });

            modelBuilder.Entity("Web_Example_Temp.Models.Öğrenci", b =>
                {
                    b.Navigation("ÖğrenciVeliler");
                });
#pragma warning restore 612, 618
        }
    }
}
